list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/AAT_LVGL_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/AAT_LVGL.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_medium_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/OpenScreen_gen.c)